version: "3"
services:
  sls:
    build: .
    container_name: sls_template
    tty: true
    volumes:
      - .:/opt/app
      - bundle:/root/.anyenv/envs/rbenv
    ports:
      - "3000:3000"
    environment:
      - DEFAULT_REGION=ap-northeast-1
      - LOCALSTACK_HOST=localstack
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}

volumes:
  bundle: